import os

from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def env_float(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError:
        return default


SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

IBKR_HOST = os.getenv("IBKR_HOST", "127.0.0.1")
IBKR_PORT = env_int("IBKR_PORT", 7497)
IBKR_CLIENT_ID = env_int("IBKR_CLIENT_ID", 10)
IBKR_SYNC_CLIENT_ID = env_int("IBKR_SYNC_CLIENT_ID", IBKR_CLIENT_ID + 1)
IBKR_CONTEXT_CLIENT_ID = env_int("IBKR_CONTEXT_CLIENT_ID", IBKR_CLIENT_ID + 2)
IBKR_NEWS_CLIENT_ID = env_int("IBKR_NEWS_CLIENT_ID", IBKR_CLIENT_ID + 3)
IBKR_PURE_TRAINING_CLIENT_ID = env_int("IBKR_PURE_TRAINING_CLIENT_ID", IBKR_CLIENT_ID + 4)
IBKR_EXPERIMENTAL_CLIENT_ID = env_int("IBKR_EXPERIMENTAL_CLIENT_ID", IBKR_CLIENT_ID + 24)
IBKR_SCANNER_CLIENT_ID = env_int("IBKR_SCANNER_CLIENT_ID", IBKR_CLIENT_ID + 30)

MARKET_TIMEZONE = os.getenv("MARKET_TIMEZONE", "US/Eastern")
PREMARKET_OPEN = os.getenv("PREMARKET_OPEN", "04:00")
REGULAR_MARKET_OPEN = os.getenv("REGULAR_MARKET_OPEN", "09:30")
REGULAR_MARKET_CLOSE = os.getenv("REGULAR_MARKET_CLOSE", "16:00")
AFTER_HOURS_CLOSE = os.getenv("AFTER_HOURS_CLOSE", "20:00")
SCAN_EXTENDED_HOURS = env_bool("SCAN_EXTENDED_HOURS", True)
ALLOW_EXTENDED_HOURS_TRADING = env_bool("ALLOW_EXTENDED_HOURS_TRADING", False)
STOP_OUTSIDE_RTH = env_bool("STOP_OUTSIDE_RTH", False)
GLOBAL_OVERNIGHT_OPEN = os.getenv("GLOBAL_OVERNIGHT_OPEN", "20:00")
GLOBAL_OVERNIGHT_CLOSE = os.getenv("GLOBAL_OVERNIGHT_CLOSE", "04:00")
SCAN_GLOBAL_OVERNIGHT = env_bool("SCAN_GLOBAL_OVERNIGHT", True)
SCAN_SUNDAY_NIGHT = env_bool("SCAN_SUNDAY_NIGHT", True)
ALLOW_GLOBAL_OVERNIGHT_TRADING = env_bool("ALLOW_GLOBAL_OVERNIGHT_TRADING", False)

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/chat")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen3.6:latest")
OLLAMA_MODEL_ROUTING_ENABLED = env_bool("OLLAMA_MODEL_ROUTING_ENABLED", True)
OLLAMA_LIVE_MODEL = os.getenv("OLLAMA_LIVE_MODEL", "nemotron-3-nano:4b")
OLLAMA_SCANNER_MODEL = os.getenv("OLLAMA_SCANNER_MODEL", "qwen3.5:latest")
OLLAMA_NEWS_MODEL = os.getenv("OLLAMA_NEWS_MODEL", OLLAMA_LIVE_MODEL)
OLLAMA_DEEP_MODEL = os.getenv("OLLAMA_DEEP_MODEL", "qwen3.6:latest")
OLLAMA_EDGE_MODEL = os.getenv("OLLAMA_EDGE_MODEL", "nemotron-3-nano:4b")
OLLAMA_GAMING_MODEL = os.getenv("OLLAMA_GAMING_MODEL", OLLAMA_LIVE_MODEL)
LLM_METRICS_ENABLED = env_bool("LLM_METRICS_ENABLED", True)
LLM_METRICS_PATH = os.getenv("LLM_METRICS_PATH", "data/llm_metrics.jsonl")
LOCAL_DATA_CAPTURE_ENABLED = env_bool("LOCAL_DATA_CAPTURE_ENABLED", True)
LOCAL_DATA_CAPTURE_PATH = os.getenv("LOCAL_DATA_CAPTURE_PATH", "data/local_training_events.jsonl")
SCRIPT_LAUNCHER_ENABLED = env_bool("SCRIPT_LAUNCHER_ENABLED", True)
SCRIPT_LAUNCHER_INTERVAL_SECONDS = env_int("SCRIPT_LAUNCHER_INTERVAL_SECONDS", 3)
SCRIPT_LAUNCHER_TABLE = os.getenv("SCRIPT_LAUNCHER_TABLE", "script_launch_requests")
PERFORMANCE_GOVERNOR_ENABLED = env_bool("PERFORMANCE_GOVERNOR_ENABLED", False)
PERFORMANCE_MODE = os.getenv("PERFORMANCE_MODE", "normal").strip().lower()
PERFORMANCE_GAME_PROCESS_NAMES = os.getenv(
    "PERFORMANCE_GAME_PROCESS_NAMES",
    "cs2.exe,valorant.exe,fortniteclient-win64-shipping.exe,cod.exe,cod22-cod.exe,"
    "r5apex.exe,overwatch.exe,destiny2.exe,helldivers2.exe,thefinals.exe,gta5.exe,"
    "eldenring.exe,cyberpunk2077.exe,starfield.exe,minecraft.exe,robloxplayerbeta.exe",
)
PERFORMANCE_BUSY_CPU_PCT = env_float("PERFORMANCE_BUSY_CPU_PCT", 78.0)
PERFORMANCE_LOW_MEMORY_GB = env_float("PERFORMANCE_LOW_MEMORY_GB", 10.0)
PERFORMANCE_PROFILE_TTL_SECONDS = env_int("PERFORMANCE_PROFILE_TTL_SECONDS", 30)
PERFORMANCE_GAMING_KEEP_ALIVE = os.getenv("PERFORMANCE_GAMING_KEEP_ALIVE", "30s")
PERFORMANCE_GAMING_TIMEOUT_SECONDS = env_int("PERFORMANCE_GAMING_TIMEOUT_SECONDS", 30)
PERFORMANCE_GAMING_MAX_NUM_PREDICT = env_int("PERFORMANCE_GAMING_MAX_NUM_PREDICT", 64)
PERFORMANCE_GAMING_MAX_BATCH_SIZE = env_int("PERFORMANCE_GAMING_MAX_BATCH_SIZE", 1)
PERFORMANCE_GAMING_MAX_LLM_ITEMS = env_int("PERFORMANCE_GAMING_MAX_LLM_ITEMS", 2)
PERFORMANCE_GAMING_MAX_WORKERS = env_int("PERFORMANCE_GAMING_MAX_WORKERS", 1)
PERFORMANCE_GAMING_MAX_LLM_TICKERS = env_int("PERFORMANCE_GAMING_MAX_LLM_TICKERS", 5)
PERFORMANCE_GAMING_INTERVAL_MULTIPLIER = env_float("PERFORMANCE_GAMING_INTERVAL_MULTIPLIER", 6.0)
PERFORMANCE_GAMING_CPU_BUDGET_PCT = env_float("PERFORMANCE_GAMING_CPU_BUDGET_PCT", 10.0)
PERFORMANCE_GAMING_THROTTLE_ENABLED = env_bool("PERFORMANCE_GAMING_THROTTLE_ENABLED", False)
PERFORMANCE_GAMING_THROTTLE_MIN_SLEEP_SECONDS = env_float("PERFORMANCE_GAMING_THROTTLE_MIN_SLEEP_SECONDS", 2.0)
PERFORMANCE_GAMING_THROTTLE_MAX_SLEEP_SECONDS = env_float("PERFORMANCE_GAMING_THROTTLE_MAX_SLEEP_SECONDS", 30.0)
PERFORMANCE_GAMING_PROCESS_PRIORITY = os.getenv("PERFORMANCE_GAMING_PROCESS_PRIORITY", "BelowNormal")
PERFORMANCE_GAMING_EXTERNAL_PRIORITY = os.getenv("PERFORMANCE_GAMING_EXTERNAL_PRIORITY", "BelowNormal")
PERFORMANCE_GAMING_EXTERNAL_PROCESSES = os.getenv("PERFORMANCE_GAMING_EXTERNAL_PROCESSES", "ollama,llama-server")
PERFORMANCE_RESTORE_PRIORITY_ON_NORMAL = env_bool("PERFORMANCE_RESTORE_PRIORITY_ON_NORMAL", True)
PERFORMANCE_DEFER_TASKS = os.getenv(
    "PERFORMANCE_DEFER_TASKS",
    "scanner:llm,operation:ticker-intel,operation:briefing,operation:post-trade-review,"
    "operation:category-universe,operation:energy-universe",
)
LLM_SCANNER_TIMEOUT_SECONDS = env_int("LLM_SCANNER_TIMEOUT_SECONDS", 90)
LLM_SCANNER_RETRY_ATTEMPTS = env_int("LLM_SCANNER_RETRY_ATTEMPTS", 2)
LLM_SCANNER_RETRY_BACKOFF_SECONDS = env_int("LLM_SCANNER_RETRY_BACKOFF_SECONDS", 2)
LLM_SCANNER_NUM_PREDICT = env_int("LLM_SCANNER_NUM_PREDICT", 180)
LLM_SCANNER_KEEP_ALIVE = os.getenv("LLM_SCANNER_KEEP_ALIVE", "30m")
LLM_SCANNER_RULES_MAX_CHARS = env_int("LLM_SCANNER_RULES_MAX_CHARS", 1800)
LLM_SCANNER_MAX_TICKERS = env_int("LLM_SCANNER_MAX_TICKERS", 0)
LLM_SCANNER_MAX_CONSECUTIVE_FAILURES = env_int("LLM_SCANNER_MAX_CONSECUTIVE_FAILURES", 8)
SIGNAL_QUALITY_FILTER_ENABLED = env_bool("SIGNAL_QUALITY_FILTER_ENABLED", True)
SIGNAL_QUALITY_MIN_SCORE = env_int("SIGNAL_QUALITY_MIN_SCORE", 55)
SIGNAL_QUALITY_TIMEOUT_SECONDS = env_int("SIGNAL_QUALITY_TIMEOUT_SECONDS", 90)
SIGNAL_QUALITY_FAIL_OPEN = env_bool("SIGNAL_QUALITY_FAIL_OPEN", True)
SIGNAL_QUALITY_FAIL_OPEN_ON_PARSE_ERROR = env_bool("SIGNAL_QUALITY_FAIL_OPEN_ON_PARSE_ERROR", True)
SIGNAL_QUALITY_NUM_PREDICT = env_int("SIGNAL_QUALITY_NUM_PREDICT", 160)
SIGNAL_QUALITY_RETRY_ATTEMPTS = env_int("SIGNAL_QUALITY_RETRY_ATTEMPTS", 2)
SIGNAL_QUALITY_RETRY_BACKOFF_SECONDS = env_int("SIGNAL_QUALITY_RETRY_BACKOFF_SECONDS", 2)
SIGNAL_QUALITY_KEEP_ALIVE = os.getenv("SIGNAL_QUALITY_KEEP_ALIVE", "30m")
EXECUTION_GATE_ENABLED = env_bool("EXECUTION_GATE_ENABLED", True)
EXECUTION_GATE_MIN_SCORE = env_int("EXECUTION_GATE_MIN_SCORE", 25)
EXECUTION_GATE_FAIL_OPEN = env_bool("EXECUTION_GATE_FAIL_OPEN", True)
EXECUTION_GATE_TIMEOUT_SECONDS = env_int("EXECUTION_GATE_TIMEOUT_SECONDS", 90)
EXECUTION_GATE_NUM_PREDICT = env_int("EXECUTION_GATE_NUM_PREDICT", 180)
EXECUTION_GATE_RETRY_ATTEMPTS = env_int("EXECUTION_GATE_RETRY_ATTEMPTS", 2)
EXECUTION_GATE_RETRY_BACKOFF_SECONDS = env_int("EXECUTION_GATE_RETRY_BACKOFF_SECONDS", 2)
EXECUTION_GATE_KEEP_ALIVE = os.getenv("EXECUTION_GATE_KEEP_ALIVE", "30m")

DRY_RUN = env_bool("DRY_RUN", True)
FIXED_ORDER_QUANTITY = env_int("FIXED_ORDER_QUANTITY", 20)
ENTRY_ORDER_TYPE = os.getenv("ENTRY_ORDER_TYPE", "MKT").strip().upper()
BRACKET_STOP_LOSS_PCT = env_float("BRACKET_STOP_LOSS_PCT", 2.0)
BRACKET_TAKE_PROFIT_PCT = env_float("BRACKET_TAKE_PROFIT_PCT", 4.0)
BUY_REENTRY_DIP_PCT = env_float("BUY_REENTRY_DIP_PCT", 10.0)
MAX_DRAWDOWN_PCT = env_float("MAX_DRAWDOWN_PCT", 2.0)
SIGNAL_COOLDOWN_MINUTES = env_int("SIGNAL_COOLDOWN_MINUTES", 240)
SIGNAL_JOURNAL_PATH = os.getenv("SIGNAL_JOURNAL_PATH", "data/signal_journal.csv")
CYCLE_LOG_ENABLED = env_bool("CYCLE_LOG_ENABLED", True)
CYCLE_LOG_PATH = os.getenv("CYCLE_LOG_PATH", "data/master_cycle_log.jsonl")
CYCLE_LOG_PUSH_SUPABASE = env_bool("CYCLE_LOG_PUSH_SUPABASE", True)
CYCLE_LOG_SIGNAL_LIMIT = env_int("CYCLE_LOG_SIGNAL_LIMIT", 250)
CYCLE_LOG_EVENT_LIMIT = env_int("CYCLE_LOG_EVENT_LIMIT", 250)
TECH_RSI_BUY_THRESHOLD = env_float("TECH_RSI_BUY_THRESHOLD", 35.0)
TECH_RSI_SELL_THRESHOLD = env_float("TECH_RSI_SELL_THRESHOLD", 75.0)
TECH_BUY_CONFIDENCE = env_float("TECH_BUY_CONFIDENCE", 82.0)
TECH_SELL_CONFIDENCE = env_float("TECH_SELL_CONFIDENCE", 80.0)
RADAR_TARGET_LIMIT = env_int("RADAR_TARGET_LIMIT", 12)
RADAR_MIN_ABS_MOVE_PCT = env_float("RADAR_MIN_ABS_MOVE_PCT", 1.0)
RADAR_ALLOW_YAHOO_TRENDING_FALLBACK = env_bool("RADAR_ALLOW_YAHOO_TRENDING_FALLBACK", False)
SCANNER_INTERVAL_SECONDS = env_int("SCANNER_INTERVAL_SECONDS", 600)
MASTER_DAILY_CATEGORY_REFRESH_TIME = os.getenv("MASTER_DAILY_CATEGORY_REFRESH_TIME", "05:30")
MASTER_EVENING_REVIEW_TIME = os.getenv("MASTER_EVENING_REVIEW_TIME", "16:30")
OPEN_SCANNER_ENABLED = env_bool("OPEN_SCANNER_ENABLED", True)
OPEN_SCANNER_START = os.getenv("OPEN_SCANNER_START", REGULAR_MARKET_OPEN)
OPEN_SCANNER_END = os.getenv("OPEN_SCANNER_END", "10:15")
OPEN_SCANNER_MINUTES_AFTER_OPEN = env_int("OPEN_SCANNER_MINUTES_AFTER_OPEN", 5)
OPEN_SCANNER_MAX_TICKERS = env_int("OPEN_SCANNER_MAX_TICKERS", 135)
OPEN_SCANNER_MIN_PRICE = env_float("OPEN_SCANNER_MIN_PRICE", 5.0)
OPEN_SCANNER_MIN_RVOL = env_float("OPEN_SCANNER_MIN_RVOL", 1.2)
OPEN_SCANNER_MIN_MOVE_PCT = env_float("OPEN_SCANNER_MIN_MOVE_PCT", 1.0)
OPEN_SCANNER_MIN_RECOVERY_PCT = env_float("OPEN_SCANNER_MIN_RECOVERY_PCT", 0.45)
OPEN_SCANNER_MIN_CONFIDENCE = env_int("OPEN_SCANNER_MIN_CONFIDENCE", 62)
OPEN_SCANNER_COOLDOWN_MINUTES = env_int("OPEN_SCANNER_COOLDOWN_MINUTES", 90)
BROKER_SYNC_INTERVAL_SECONDS = env_int("BROKER_SYNC_INTERVAL_SECONDS", 30)
BROKER_SYNC_MARK_MISSING_SIGNALS = env_bool("BROKER_SYNC_MARK_MISSING_SIGNALS", False)
SYNC_BROKER_AFTER_ORDER = env_bool("SYNC_BROKER_AFTER_ORDER", True)
SYNC_BROKER_AFTER_ORDER_DELAY_SECONDS = env_float("SYNC_BROKER_AFTER_ORDER_DELAY_SECONDS", 2.0)
PURE_TRAINING_MODE_ENABLED = env_bool("PURE_TRAINING_MODE_ENABLED", False)
PURE_TRAINING_ORDER_QUANTITY = env_int("PURE_TRAINING_ORDER_QUANTITY", 2)
PURE_TRAINING_MAX_ACCOUNT_CAD = env_float("PURE_TRAINING_MAX_ACCOUNT_CAD", 1_000_000.0)
PURE_TRAINING_MIN_CASH_BUFFER_CAD = env_float("PURE_TRAINING_MIN_CASH_BUFFER_CAD", 5_000.0)
PURE_TRAINING_USD_CAD_RATE = env_float("PURE_TRAINING_USD_CAD_RATE", 1.40)
PURE_TRAINING_MAX_POSITION_PER_TICKER = env_int("PURE_TRAINING_MAX_POSITION_PER_TICKER", 2)
PURE_TRAINING_MAX_TICKERS_PER_RUN = env_int("PURE_TRAINING_MAX_TICKERS_PER_RUN", 0)
PURE_TRAINING_SYNC_EVERY_ORDERS = env_int("PURE_TRAINING_SYNC_EVERY_ORDERS", 10)
PURE_TRAINING_LOCAL_LOG_PATH = os.getenv("PURE_TRAINING_LOCAL_LOG_PATH", "data/pure_training_runs.jsonl")
PURE_TRAINING_ADAPTATION_PATH = os.getenv("PURE_TRAINING_ADAPTATION_PATH", "data/pure_training_adaptation.json")
PURE_TRAINING_MONITOR_INTERVAL_SECONDS = env_int("PURE_TRAINING_MONITOR_INTERVAL_SECONDS", 300)
PURE_TRAINING_REVIEW_TIME = os.getenv("PURE_TRAINING_REVIEW_TIME", MASTER_EVENING_REVIEW_TIME)
PURE_TRAINING_ORDER_REF_PREFIX = os.getenv("PURE_TRAINING_ORDER_REF_PREFIX", "PURETRAIN")
EXPERIMENTAL_MODE_ENABLED = env_bool("EXPERIMENTAL_MODE_ENABLED", PURE_TRAINING_MODE_ENABLED)
EXPERIMENTAL_MIN_MONTHLY_VOLATILITY_PCT = env_float("EXPERIMENTAL_MIN_MONTHLY_VOLATILITY_PCT", 5.0)
EXPERIMENTAL_SESSION_DUPLICATE_GUARD = env_bool("EXPERIMENTAL_SESSION_DUPLICATE_GUARD", True)
EXPERIMENTAL_LOCAL_LOG_PATH = os.getenv("EXPERIMENTAL_LOCAL_LOG_PATH", PURE_TRAINING_LOCAL_LOG_PATH)
EXPERIMENTAL_ORDER_REF_PREFIX = os.getenv("EXPERIMENTAL_ORDER_REF_PREFIX", PURE_TRAINING_ORDER_REF_PREFIX)
EXPERIMENTAL_USE_IBKR_MARKET_DATA = env_bool("EXPERIMENTAL_USE_IBKR_MARKET_DATA", False)
MASSIVE_API_KEY = os.getenv("MASSIVE_API_KEY")
MASSIVE_PREV_CLOSE_ENABLED = env_bool("MASSIVE_PREV_CLOSE_ENABLED", True)
SIGNAL_CONTEXT_LIMIT = env_int("SIGNAL_CONTEXT_LIMIT", 50)
ENERGY_TARGET_LIMIT = env_int("ENERGY_TARGET_LIMIT", 50)
ENERGY_MIN_SCORE = env_float("ENERGY_MIN_SCORE", 70.0)
CATEGORY_UNIVERSE_LIMIT = env_int("CATEGORY_UNIVERSE_LIMIT", 7000)
CATEGORY_MIN_SCORE = env_float("CATEGORY_MIN_SCORE", 65.0)
CATEGORY_TARGET_LIMIT = env_int("CATEGORY_TARGET_LIMIT", 135)
CATEGORY_TARGETS_PER_CATEGORY = env_int("CATEGORY_TARGETS_PER_CATEGORY", 15)
SIGNAL_SOURCES_ENABLED = env_bool("SIGNAL_SOURCES_ENABLED", True)
SIGNAL_SOURCE_OUTPUT_PATH = os.getenv("SIGNAL_SOURCE_OUTPUT_PATH", "data/signal_source_runs.jsonl")
SIGNAL_SOURCE_MAX_CANDIDATES = env_int("SIGNAL_SOURCE_MAX_CANDIDATES", 160)
SIGNAL_SOURCE_USE_YAHOO_UNIVERSE = env_bool("SIGNAL_SOURCE_USE_YAHOO_UNIVERSE", True)
SIGNAL_SOURCE_USE_IBKR_SCANNER = env_bool("SIGNAL_SOURCE_USE_IBKR_SCANNER", True)
SIGNAL_SOURCE_USE_IBKR_NEWS = env_bool("SIGNAL_SOURCE_USE_IBKR_NEWS", True)
IBKR_SCANNER_LOCATION_CODE = os.getenv("IBKR_SCANNER_LOCATION_CODE", "STK.US.MAJOR")
IBKR_SCANNER_SCAN_CODES = os.getenv("IBKR_SCANNER_SCAN_CODES", "HOT_BY_VOLUME,TOP_PERC_GAIN,TOP_PERC_LOSE,MOST_ACTIVE")
IBKR_SCANNER_LIMIT_PER_CODE = env_int("IBKR_SCANNER_LIMIT_PER_CODE", 20)
TECH_NEWS_TICKERS = os.getenv(
    "TECH_NEWS_TICKERS",
    "AAPL,MSFT,NVDA,AMD,AVGO,AMZN,META,GOOGL,TSLA,ORCL,CRM,ADBE,NFLX,INTC,QCOM,MU,IBM,TSM,ASML,ARM,PLTR,SMCI,NOW,SNOW,PANW,CRWD,DDOG,NET",
)
TECH_NEWS_INTERVAL_SECONDS = env_int("TECH_NEWS_INTERVAL_SECONDS", 180)
TECH_NEWS_MAX_WORKERS = env_int("TECH_NEWS_MAX_WORKERS", 8)
TECH_NEWS_LIMIT_PER_TICKER = env_int("TECH_NEWS_LIMIT_PER_TICKER", 5)
TECH_NEWS_OUTPUT_PATH = os.getenv("TECH_NEWS_OUTPUT_PATH", "data/tech_news_feed.jsonl")
TECH_NEWS_RELEVANCE_FILTER_ENABLED = env_bool("TECH_NEWS_RELEVANCE_FILTER_ENABLED", True)
TECH_NEWS_RELEVANCE_MIN_SCORE = env_int("TECH_NEWS_RELEVANCE_MIN_SCORE", 2)
TECH_NEWS_LLM_ENABLED = env_bool("TECH_NEWS_LLM_ENABLED", True)
TECH_NEWS_LLM_MAX_ITEMS = env_int("TECH_NEWS_LLM_MAX_ITEMS", 20)
TECH_NEWS_LLM_TIMEOUT_SECONDS = env_int("TECH_NEWS_LLM_TIMEOUT_SECONDS", 120)
TECH_NEWS_LLM_BATCH_SIZE = env_int("TECH_NEWS_LLM_BATCH_SIZE", 3)
TECH_NEWS_LLM_NUM_PREDICT = env_int("TECH_NEWS_LLM_NUM_PREDICT", 140)
TECH_NEWS_LLM_NUM_PREDICT_PER_ITEM = env_int("TECH_NEWS_LLM_NUM_PREDICT_PER_ITEM", 120)
TECH_NEWS_LLM_SINGLE_TIMEOUT_SECONDS = env_int("TECH_NEWS_LLM_SINGLE_TIMEOUT_SECONDS", 45)
TECH_NEWS_LLM_SINGLE_NUM_PREDICT = env_int("TECH_NEWS_LLM_SINGLE_NUM_PREDICT", 96)
TECH_NEWS_LLM_DEFAULT_RETRY_LIMIT = env_int("TECH_NEWS_LLM_DEFAULT_RETRY_LIMIT", 20)
TECH_NEWS_LLM_RETRY_ATTEMPTS = env_int("TECH_NEWS_LLM_RETRY_ATTEMPTS", 2)
TECH_NEWS_LLM_RETRY_BACKOFF_SECONDS = env_int("TECH_NEWS_LLM_RETRY_BACKOFF_SECONDS", 2)
TECH_NEWS_LLM_KEEP_ALIVE = os.getenv("TECH_NEWS_LLM_KEEP_ALIVE", "30m")
TECH_NEWS_LLM_WARMUP = env_bool("TECH_NEWS_LLM_WARMUP", True)
TICKER_INTEL_OUTPUT_PATH = os.getenv("TICKER_INTEL_OUTPUT_PATH", "data/ticker_intelligence.jsonl")
TICKER_INTEL_NEWS_LIMIT = env_int("TICKER_INTEL_NEWS_LIMIT", 8)
TICKER_INTEL_CHATTER_LIMIT = env_int("TICKER_INTEL_CHATTER_LIMIT", 10)
TICKER_INTEL_SIGNAL_LOOKBACK_DAYS = env_int("TICKER_INTEL_SIGNAL_LOOKBACK_DAYS", 14)
TICKER_INTEL_WATCHLIST_LIMIT = env_int("TICKER_INTEL_WATCHLIST_LIMIT", 100)
TICKER_INTEL_PUSH_SUPABASE = env_bool("TICKER_INTEL_PUSH_SUPABASE", True)
IBKR_NEWS_ENABLED = env_bool("IBKR_NEWS_ENABLED", True)
IBKR_NEWS_PROVIDERS = os.getenv("IBKR_NEWS_PROVIDERS", "")
IBKR_NEWS_LOOKBACK_MINUTES = env_int("IBKR_NEWS_LOOKBACK_MINUTES", 30)
IBKR_NEWS_INTERVAL_SECONDS = env_int("IBKR_NEWS_INTERVAL_SECONDS", 60)
IBKR_NEWS_MAX_TICKERS = env_int("IBKR_NEWS_MAX_TICKERS", 135)
IBKR_NEWS_RESULTS_PER_TICKER = env_int("IBKR_NEWS_RESULTS_PER_TICKER", 5)
IBKR_NEWS_MIN_CONFIDENCE = env_int("IBKR_NEWS_MIN_CONFIDENCE", 62)
IBKR_NEWS_MIN_DIRECTIONAL_SCORE = env_int("IBKR_NEWS_MIN_DIRECTIONAL_SCORE", 1)
IBKR_NEWS_COOLDOWN_MINUTES = env_int("IBKR_NEWS_COOLDOWN_MINUTES", 90)
IBKR_NEWS_OUTPUT_PATH = os.getenv("IBKR_NEWS_OUTPUT_PATH", "data/ibkr_news_feed.jsonl")
IBKR_NEWS_SEEN_PATH = os.getenv("IBKR_NEWS_SEEN_PATH", "data/ibkr_news_seen.json")
IBKR_NEWS_PUSH_SIGNALS = env_bool("IBKR_NEWS_PUSH_SIGNALS", True)
MARKET_BRIEFING_LOOKBACK_HOURS = env_int("MARKET_BRIEFING_LOOKBACK_HOURS", 12)
MARKET_BRIEFING_NEWS_LIMIT = env_int("MARKET_BRIEFING_NEWS_LIMIT", 30)
MARKET_BRIEFING_SIGNAL_LIMIT = env_int("MARKET_BRIEFING_SIGNAL_LIMIT", 30)
MARKET_BRIEFING_POSITION_LIMIT = env_int("MARKET_BRIEFING_POSITION_LIMIT", 20)
MARKET_BRIEFING_CATEGORY_LIMIT = env_int("MARKET_BRIEFING_CATEGORY_LIMIT", 10)
MARKET_BRIEFING_TIMEOUT_SECONDS = env_int("MARKET_BRIEFING_TIMEOUT_SECONDS", 120)
MARKET_BRIEFING_OUTPUT_PATH = os.getenv("MARKET_BRIEFING_OUTPUT_PATH", "data/daily_market_briefings.jsonl")
MARKET_BRIEFING_PUSH_SUPABASE = env_bool("MARKET_BRIEFING_PUSH_SUPABASE", True)
POST_TRADE_REVIEW_LOOKBACK_DAYS = env_int("POST_TRADE_REVIEW_LOOKBACK_DAYS", 14)
POST_TRADE_REVIEW_LIMIT = env_int("POST_TRADE_REVIEW_LIMIT", 25)
POST_TRADE_REVIEW_HORIZON = os.getenv("POST_TRADE_REVIEW_HORIZON", "1d")
POST_TRADE_REVIEW_TIMEOUT_SECONDS = env_int("POST_TRADE_REVIEW_TIMEOUT_SECONDS", 120)
POST_TRADE_REVIEW_OUTPUT_PATH = os.getenv("POST_TRADE_REVIEW_OUTPUT_PATH", "data/post_trade_reviews.jsonl")
POST_TRADE_REVIEW_PUSH_SUPABASE = env_bool("POST_TRADE_REVIEW_PUSH_SUPABASE", True)
STRATEGY_OPTIMIZER_LOOKBACK_DAYS = env_int("STRATEGY_OPTIMIZER_LOOKBACK_DAYS", 14)
STRATEGY_OPTIMIZER_HORIZON = os.getenv("STRATEGY_OPTIMIZER_HORIZON", "1h")
STRATEGY_OPTIMIZER_MIN_EVALUATED_SIGNALS = env_int("STRATEGY_OPTIMIZER_MIN_EVALUATED_SIGNALS", 12)
STRATEGY_OPTIMIZER_MIN_CHANNEL_SIGNALS = env_int("STRATEGY_OPTIMIZER_MIN_CHANNEL_SIGNALS", 5)
STRATEGY_OPTIMIZER_MIN_CONFIDENCE_FLOOR = env_float("STRATEGY_OPTIMIZER_MIN_CONFIDENCE_FLOOR", 0.55)
STRATEGY_OPTIMIZER_MIN_CONFIDENCE_CEILING = env_float("STRATEGY_OPTIMIZER_MIN_CONFIDENCE_CEILING", 0.95)
STRATEGY_OPTIMIZER_MAX_STEP = env_float("STRATEGY_OPTIMIZER_MAX_STEP", 0.03)
STRATEGY_OPTIMIZER_OUTPUT_PATH = os.getenv("STRATEGY_OPTIMIZER_OUTPUT_PATH", "data/strategy_optimizer_runs.jsonl")
STRATEGY_OPTIMIZER_PUSH_SUPABASE = env_bool("STRATEGY_OPTIMIZER_PUSH_SUPABASE", True)
STRATEGY_OPTIMIZER_AUTO_APPLY = env_bool("STRATEGY_OPTIMIZER_AUTO_APPLY", False)


def resolve_ollama_model(role=None, gaming=False):
    if not OLLAMA_MODEL_ROUTING_ENABLED:
        return OLLAMA_MODEL

    if gaming and OLLAMA_GAMING_MODEL:
        return OLLAMA_GAMING_MODEL

    normalized = str(role or "default").strip().lower().replace("-", "_")
    role_models = {
        "default": OLLAMA_MODEL,
        "live": OLLAMA_LIVE_MODEL,
        "live_gate": OLLAMA_LIVE_MODEL,
        "execution_gate": OLLAMA_LIVE_MODEL,
        "signal_quality": OLLAMA_LIVE_MODEL,
        "scanner": OLLAMA_SCANNER_MODEL,
        "llm_scanner": OLLAMA_SCANNER_MODEL,
        "news": OLLAMA_NEWS_MODEL,
        "tech_news": OLLAMA_NEWS_MODEL,
        "briefing": OLLAMA_DEEP_MODEL,
        "review": OLLAMA_DEEP_MODEL,
        "post_trade_review": OLLAMA_DEEP_MODEL,
        "deep": OLLAMA_DEEP_MODEL,
        "edge": OLLAMA_EDGE_MODEL,
        "jetson": OLLAMA_EDGE_MODEL,
    }
    return role_models.get(normalized) or OLLAMA_MODEL


def get_supabase_client() -> Client:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise RuntimeError("Missing SUPABASE_URL or SUPABASE_KEY in .env.")
    return create_client(SUPABASE_URL, SUPABASE_KEY)
