import os

from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def env_float(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError:
        return default


SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

IBKR_HOST = os.getenv("IBKR_HOST", "127.0.0.1")
IBKR_PORT = env_int("IBKR_PORT", 7497)
IBKR_CLIENT_ID = env_int("IBKR_CLIENT_ID", 10)
IBKR_SYNC_CLIENT_ID = env_int("IBKR_SYNC_CLIENT_ID", IBKR_CLIENT_ID + 1)
IBKR_CONTEXT_CLIENT_ID = env_int("IBKR_CONTEXT_CLIENT_ID", IBKR_CLIENT_ID + 2)

MARKET_TIMEZONE = os.getenv("MARKET_TIMEZONE", "US/Eastern")
PREMARKET_OPEN = os.getenv("PREMARKET_OPEN", "04:00")
REGULAR_MARKET_OPEN = os.getenv("REGULAR_MARKET_OPEN", "09:30")
REGULAR_MARKET_CLOSE = os.getenv("REGULAR_MARKET_CLOSE", "16:00")
AFTER_HOURS_CLOSE = os.getenv("AFTER_HOURS_CLOSE", "20:00")
SCAN_EXTENDED_HOURS = env_bool("SCAN_EXTENDED_HOURS", True)
ALLOW_EXTENDED_HOURS_TRADING = env_bool("ALLOW_EXTENDED_HOURS_TRADING", False)
STOP_OUTSIDE_RTH = env_bool("STOP_OUTSIDE_RTH", False)
GLOBAL_OVERNIGHT_OPEN = os.getenv("GLOBAL_OVERNIGHT_OPEN", "20:00")
GLOBAL_OVERNIGHT_CLOSE = os.getenv("GLOBAL_OVERNIGHT_CLOSE", "04:00")
SCAN_GLOBAL_OVERNIGHT = env_bool("SCAN_GLOBAL_OVERNIGHT", True)
SCAN_SUNDAY_NIGHT = env_bool("SCAN_SUNDAY_NIGHT", True)
ALLOW_GLOBAL_OVERNIGHT_TRADING = env_bool("ALLOW_GLOBAL_OVERNIGHT_TRADING", False)

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:7b")
SIGNAL_QUALITY_FILTER_ENABLED = env_bool("SIGNAL_QUALITY_FILTER_ENABLED", True)
SIGNAL_QUALITY_MIN_SCORE = env_int("SIGNAL_QUALITY_MIN_SCORE", 65)
SIGNAL_QUALITY_TIMEOUT_SECONDS = env_int("SIGNAL_QUALITY_TIMEOUT_SECONDS", 90)
SIGNAL_QUALITY_FAIL_OPEN = env_bool("SIGNAL_QUALITY_FAIL_OPEN", True)

DRY_RUN = env_bool("DRY_RUN", True)
FIXED_ORDER_QUANTITY = env_int("FIXED_ORDER_QUANTITY", 100)
MAX_DRAWDOWN_PCT = env_float("MAX_DRAWDOWN_PCT", 2.0)
SIGNAL_COOLDOWN_MINUTES = env_int("SIGNAL_COOLDOWN_MINUTES", 240)
SIGNAL_JOURNAL_PATH = os.getenv("SIGNAL_JOURNAL_PATH", "data/signal_journal.csv")
SCANNER_INTERVAL_SECONDS = env_int("SCANNER_INTERVAL_SECONDS", 600)
BROKER_SYNC_INTERVAL_SECONDS = env_int("BROKER_SYNC_INTERVAL_SECONDS", 30)
BROKER_SYNC_MARK_MISSING_SIGNALS = env_bool("BROKER_SYNC_MARK_MISSING_SIGNALS", False)
MASSIVE_API_KEY = os.getenv("MASSIVE_API_KEY")
MASSIVE_PREV_CLOSE_ENABLED = env_bool("MASSIVE_PREV_CLOSE_ENABLED", True)
SIGNAL_CONTEXT_LIMIT = env_int("SIGNAL_CONTEXT_LIMIT", 50)
ENERGY_TARGET_LIMIT = env_int("ENERGY_TARGET_LIMIT", 50)
ENERGY_MIN_SCORE = env_float("ENERGY_MIN_SCORE", 70.0)
CATEGORY_UNIVERSE_LIMIT = env_int("CATEGORY_UNIVERSE_LIMIT", 7000)
CATEGORY_MIN_SCORE = env_float("CATEGORY_MIN_SCORE", 65.0)
CATEGORY_TARGET_LIMIT = env_int("CATEGORY_TARGET_LIMIT", 60)
CATEGORY_TARGETS_PER_CATEGORY = env_int("CATEGORY_TARGETS_PER_CATEGORY", 15)
TECH_NEWS_TICKERS = os.getenv(
    "TECH_NEWS_TICKERS",
    "AAPL,MSFT,NVDA,AMD,AVGO,AMZN,META,GOOGL,TSLA,ORCL,CRM,ADBE,NFLX,INTC,QCOM,MU,IBM,TSM,ASML,ARM,PLTR,SMCI,NOW,SNOW,PANW,CRWD,DDOG,NET",
)
TECH_NEWS_INTERVAL_SECONDS = env_int("TECH_NEWS_INTERVAL_SECONDS", 180)
TECH_NEWS_MAX_WORKERS = env_int("TECH_NEWS_MAX_WORKERS", 8)
TECH_NEWS_LIMIT_PER_TICKER = env_int("TECH_NEWS_LIMIT_PER_TICKER", 5)
TECH_NEWS_OUTPUT_PATH = os.getenv("TECH_NEWS_OUTPUT_PATH", "data/tech_news_feed.jsonl")
TECH_NEWS_LLM_ENABLED = env_bool("TECH_NEWS_LLM_ENABLED", True)
TECH_NEWS_LLM_MAX_ITEMS = env_int("TECH_NEWS_LLM_MAX_ITEMS", 20)
TECH_NEWS_LLM_TIMEOUT_SECONDS = env_int("TECH_NEWS_LLM_TIMEOUT_SECONDS", 90)
MARKET_BRIEFING_LOOKBACK_HOURS = env_int("MARKET_BRIEFING_LOOKBACK_HOURS", 12)
MARKET_BRIEFING_NEWS_LIMIT = env_int("MARKET_BRIEFING_NEWS_LIMIT", 30)
MARKET_BRIEFING_SIGNAL_LIMIT = env_int("MARKET_BRIEFING_SIGNAL_LIMIT", 30)
MARKET_BRIEFING_POSITION_LIMIT = env_int("MARKET_BRIEFING_POSITION_LIMIT", 20)
MARKET_BRIEFING_CATEGORY_LIMIT = env_int("MARKET_BRIEFING_CATEGORY_LIMIT", 10)
MARKET_BRIEFING_TIMEOUT_SECONDS = env_int("MARKET_BRIEFING_TIMEOUT_SECONDS", 120)
MARKET_BRIEFING_OUTPUT_PATH = os.getenv("MARKET_BRIEFING_OUTPUT_PATH", "data/daily_market_briefings.jsonl")
MARKET_BRIEFING_PUSH_SUPABASE = env_bool("MARKET_BRIEFING_PUSH_SUPABASE", True)
POST_TRADE_REVIEW_LOOKBACK_DAYS = env_int("POST_TRADE_REVIEW_LOOKBACK_DAYS", 14)
POST_TRADE_REVIEW_LIMIT = env_int("POST_TRADE_REVIEW_LIMIT", 25)
POST_TRADE_REVIEW_HORIZON = os.getenv("POST_TRADE_REVIEW_HORIZON", "1d")
POST_TRADE_REVIEW_TIMEOUT_SECONDS = env_int("POST_TRADE_REVIEW_TIMEOUT_SECONDS", 120)
POST_TRADE_REVIEW_OUTPUT_PATH = os.getenv("POST_TRADE_REVIEW_OUTPUT_PATH", "data/post_trade_reviews.jsonl")
POST_TRADE_REVIEW_PUSH_SUPABASE = env_bool("POST_TRADE_REVIEW_PUSH_SUPABASE", True)


def get_supabase_client() -> Client:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise RuntimeError("Missing SUPABASE_URL or SUPABASE_KEY in .env.")
    return create_client(SUPABASE_URL, SUPABASE_KEY)
