import argparse
import json
from datetime import datetime, timezone

from config import (
    ALLOW_EXTENDED_HOURS_TRADING,
    ALLOW_GLOBAL_OVERNIGHT_TRADING,
    BRACKET_STOP_LOSS_PCT,
    BRACKET_TAKE_PROFIT_PCT,
    BUY_REENTRY_DIP_PCT,
    CATEGORY_MIN_SCORE,
    CATEGORY_TARGET_LIMIT,
    CATEGORY_TARGETS_PER_CATEGORY,
    CATEGORY_UNIVERSE_LIMIT,
    CYCLE_LOG_ENABLED,
    CYCLE_LOG_EVENT_LIMIT,
    CYCLE_LOG_PATH,
    CYCLE_LOG_PUSH_SUPABASE,
    CYCLE_LOG_SIGNAL_LIMIT,
    DRY_RUN,
    ENTRY_ORDER_TYPE,
    EXPERIMENTAL_LOCAL_LOG_PATH,
    EXPERIMENTAL_MIN_MONTHLY_VOLATILITY_PCT,
    EXPERIMENTAL_MODE_ENABLED,
    EXPERIMENTAL_ORDER_REF_PREFIX,
    EXPERIMENTAL_SESSION_DUPLICATE_GUARD,
    EXECUTION_GATE_ENABLED,
    EXECUTION_GATE_FAIL_OPEN,
    EXECUTION_GATE_KEEP_ALIVE,
    EXECUTION_GATE_MIN_SCORE,
    EXECUTION_GATE_NUM_PREDICT,
    EXECUTION_GATE_RETRY_ATTEMPTS,
    EXECUTION_GATE_TIMEOUT_SECONDS,
    FIXED_ORDER_QUANTITY,
    GLOBAL_OVERNIGHT_CLOSE,
    GLOBAL_OVERNIGHT_OPEN,
    IBKR_NEWS_ENABLED,
    IBKR_NEWS_INTERVAL_SECONDS,
    IBKR_NEWS_MAX_TICKERS,
    IBKR_NEWS_MIN_CONFIDENCE,
    IBKR_NEWS_PUSH_SIGNALS,
    LLM_SCANNER_KEEP_ALIVE,
    LLM_SCANNER_MAX_CONSECUTIVE_FAILURES,
    LLM_SCANNER_MAX_TICKERS,
    LLM_SCANNER_NUM_PREDICT,
    LLM_SCANNER_TIMEOUT_SECONDS,
    LOCAL_DATA_CAPTURE_ENABLED,
    LOCAL_DATA_CAPTURE_PATH,
    MARKET_TIMEZONE,
    MASTER_DAILY_CATEGORY_REFRESH_TIME,
    MASTER_EVENING_REVIEW_TIME,
    MAX_DRAWDOWN_PCT,
    PURE_TRAINING_LOCAL_LOG_PATH,
    PURE_TRAINING_ADAPTATION_PATH,
    PURE_TRAINING_MAX_ACCOUNT_CAD,
    PURE_TRAINING_MAX_POSITION_PER_TICKER,
    PURE_TRAINING_MAX_TICKERS_PER_RUN,
    PURE_TRAINING_MIN_CASH_BUFFER_CAD,
    PURE_TRAINING_MODE_ENABLED,
    PURE_TRAINING_MONITOR_INTERVAL_SECONDS,
    PURE_TRAINING_ORDER_QUANTITY,
    PURE_TRAINING_REVIEW_TIME,
    PURE_TRAINING_SYNC_EVERY_ORDERS,
    PURE_TRAINING_USD_CAD_RATE,
    OLLAMA_DEEP_MODEL,
    OLLAMA_EDGE_MODEL,
    OLLAMA_GAMING_MODEL,
    OLLAMA_LIVE_MODEL,
    OLLAMA_MODEL,
    OLLAMA_MODEL_ROUTING_ENABLED,
    OLLAMA_NEWS_MODEL,
    OLLAMA_SCANNER_MODEL,
    OLLAMA_URL,
    OPEN_SCANNER_ENABLED,
    OPEN_SCANNER_END,
    OPEN_SCANNER_MAX_TICKERS,
    OPEN_SCANNER_MIN_CONFIDENCE,
    OPEN_SCANNER_MIN_MOVE_PCT,
    OPEN_SCANNER_MIN_RECOVERY_PCT,
    OPEN_SCANNER_MIN_RVOL,
    OPEN_SCANNER_START,
    PERFORMANCE_BUSY_CPU_PCT,
    PERFORMANCE_DEFER_TASKS,
    PERFORMANCE_GAMING_CPU_BUDGET_PCT,
    PERFORMANCE_GAMING_INTERVAL_MULTIPLIER,
    PERFORMANCE_GAMING_MAX_BATCH_SIZE,
    PERFORMANCE_GAMING_MAX_LLM_ITEMS,
    PERFORMANCE_GAMING_MAX_LLM_TICKERS,
    PERFORMANCE_GAMING_MAX_NUM_PREDICT,
    PERFORMANCE_GAMING_MAX_WORKERS,
    PERFORMANCE_GAMING_PROCESS_PRIORITY,
    PERFORMANCE_GAMING_THROTTLE_ENABLED,
    PERFORMANCE_GAMING_THROTTLE_MAX_SLEEP_SECONDS,
    PERFORMANCE_GAMING_THROTTLE_MIN_SLEEP_SECONDS,
    PERFORMANCE_GOVERNOR_ENABLED,
    PERFORMANCE_MODE,
    PREMARKET_OPEN,
    RADAR_ALLOW_YAHOO_TRENDING_FALLBACK,
    RADAR_MIN_ABS_MOVE_PCT,
    RADAR_TARGET_LIMIT,
    REGULAR_MARKET_CLOSE,
    REGULAR_MARKET_OPEN,
    AFTER_HOURS_CLOSE,
    SCAN_EXTENDED_HOURS,
    SCAN_GLOBAL_OVERNIGHT,
    SCAN_SUNDAY_NIGHT,
    SCANNER_INTERVAL_SECONDS,
    SIGNAL_COOLDOWN_MINUTES,
    SIGNAL_QUALITY_FAIL_OPEN,
    SIGNAL_QUALITY_FAIL_OPEN_ON_PARSE_ERROR,
    SIGNAL_QUALITY_FILTER_ENABLED,
    SIGNAL_QUALITY_KEEP_ALIVE,
    SIGNAL_QUALITY_MIN_SCORE,
    SIGNAL_QUALITY_NUM_PREDICT,
    SIGNAL_QUALITY_RETRY_ATTEMPTS,
    SIGNAL_QUALITY_TIMEOUT_SECONDS,
    STOP_OUTSIDE_RTH,
    SYNC_BROKER_AFTER_ORDER,
    SYNC_BROKER_AFTER_ORDER_DELAY_SECONDS,
    TECH_BUY_CONFIDENCE,
    TECH_NEWS_LLM_BATCH_SIZE,
    TECH_NEWS_LLM_ENABLED,
    TECH_NEWS_LLM_KEEP_ALIVE,
    TECH_NEWS_LLM_MAX_ITEMS,
    TECH_NEWS_LLM_TIMEOUT_SECONDS,
    TECH_NEWS_RELEVANCE_FILTER_ENABLED,
    TECH_NEWS_RELEVANCE_MIN_SCORE,
    TECH_RSI_BUY_THRESHOLD,
    TECH_RSI_SELL_THRESHOLD,
    TECH_SELL_CONFIDENCE,
    get_supabase_client,
)


def build_runtime_config_snapshot():
    from category_target_scanner import DEFAULT_CATEGORIES

    return {
        "id": 1,
        "source": "windows_bot",
        "risk_settings": {
            "dry_run": DRY_RUN,
            "fixed_order_quantity": FIXED_ORDER_QUANTITY,
            "entry_order_type": ENTRY_ORDER_TYPE,
            "stop_loss_percent": BRACKET_STOP_LOSS_PCT,
            "take_profit_percent": BRACKET_TAKE_PROFIT_PCT,
            "buy_reentry_dip_percent": BUY_REENTRY_DIP_PCT,
            "max_drawdown_percent": MAX_DRAWDOWN_PCT,
            "signal_cooldown_minutes": SIGNAL_COOLDOWN_MINUTES,
            "execution_gate_enabled": EXECUTION_GATE_ENABLED,
            "execution_gate_min_score": EXECUTION_GATE_MIN_SCORE,
            "execution_gate_fail_open": EXECUTION_GATE_FAIL_OPEN,
            "sync_broker_after_order": SYNC_BROKER_AFTER_ORDER,
            "sync_broker_after_order_delay_seconds": SYNC_BROKER_AFTER_ORDER_DELAY_SECONDS,
            "pure_training_mode_enabled": PURE_TRAINING_MODE_ENABLED,
            "pure_training_order_quantity": PURE_TRAINING_ORDER_QUANTITY,
            "pure_training_max_account_cad": PURE_TRAINING_MAX_ACCOUNT_CAD,
            "pure_training_min_cash_buffer_cad": PURE_TRAINING_MIN_CASH_BUFFER_CAD,
            "pure_training_usd_cad_rate": PURE_TRAINING_USD_CAD_RATE,
            "pure_training_max_position_per_ticker": PURE_TRAINING_MAX_POSITION_PER_TICKER,
            "pure_training_max_tickers_per_run": PURE_TRAINING_MAX_TICKERS_PER_RUN,
            "pure_training_sync_every_orders": PURE_TRAINING_SYNC_EVERY_ORDERS,
            "pure_training_local_log_path": PURE_TRAINING_LOCAL_LOG_PATH,
            "pure_training_adaptation_path": PURE_TRAINING_ADAPTATION_PATH,
            "pure_training_monitor_interval_seconds": PURE_TRAINING_MONITOR_INTERVAL_SECONDS,
            "pure_training_review_time": PURE_TRAINING_REVIEW_TIME,
            "experimental_mode_enabled": EXPERIMENTAL_MODE_ENABLED,
            "experimental_min_monthly_volatility_pct": EXPERIMENTAL_MIN_MONTHLY_VOLATILITY_PCT,
            "experimental_session_duplicate_guard": EXPERIMENTAL_SESSION_DUPLICATE_GUARD,
            "experimental_local_log_path": EXPERIMENTAL_LOCAL_LOG_PATH,
            "experimental_order_ref_prefix": EXPERIMENTAL_ORDER_REF_PREFIX,
        },
        "scanner_settings": {
            "scanner_interval_seconds": SCANNER_INTERVAL_SECONDS,
            "daily_category_refresh_time": MASTER_DAILY_CATEGORY_REFRESH_TIME,
            "evening_review_time": MASTER_EVENING_REVIEW_TIME,
            "category_universe_limit": CATEGORY_UNIVERSE_LIMIT,
            "category_min_score": CATEGORY_MIN_SCORE,
            "category_target_limit": CATEGORY_TARGET_LIMIT,
            "category_targets_per_category": CATEGORY_TARGETS_PER_CATEGORY,
            "category_names": DEFAULT_CATEGORIES,
            "cycle_log_enabled": CYCLE_LOG_ENABLED,
            "cycle_log_path": CYCLE_LOG_PATH,
            "cycle_log_push_supabase": CYCLE_LOG_PUSH_SUPABASE,
            "cycle_log_signal_limit": CYCLE_LOG_SIGNAL_LIMIT,
            "cycle_log_event_limit": CYCLE_LOG_EVENT_LIMIT,
            "local_data_capture_enabled": LOCAL_DATA_CAPTURE_ENABLED,
            "local_data_capture_path": LOCAL_DATA_CAPTURE_PATH,
            "opening_scanner_enabled": OPEN_SCANNER_ENABLED,
            "opening_scanner_start": OPEN_SCANNER_START,
            "opening_scanner_end": OPEN_SCANNER_END,
            "opening_scanner_max_tickers": OPEN_SCANNER_MAX_TICKERS,
            "opening_scanner_min_confidence": OPEN_SCANNER_MIN_CONFIDENCE,
            "opening_scanner_min_move_percent": OPEN_SCANNER_MIN_MOVE_PCT,
            "opening_scanner_min_recovery_percent": OPEN_SCANNER_MIN_RECOVERY_PCT,
            "opening_scanner_min_rvol": OPEN_SCANNER_MIN_RVOL,
            "ibkr_news_enabled": IBKR_NEWS_ENABLED,
            "ibkr_news_interval_seconds": IBKR_NEWS_INTERVAL_SECONDS,
            "ibkr_news_max_tickers": IBKR_NEWS_MAX_TICKERS,
            "ibkr_news_min_confidence": IBKR_NEWS_MIN_CONFIDENCE,
            "ibkr_news_push_signals": IBKR_NEWS_PUSH_SIGNALS,
            "tech_rsi_buy_threshold": TECH_RSI_BUY_THRESHOLD,
            "tech_rsi_sell_threshold": TECH_RSI_SELL_THRESHOLD,
            "tech_buy_confidence": TECH_BUY_CONFIDENCE,
            "tech_sell_confidence": TECH_SELL_CONFIDENCE,
            "radar_target_limit": RADAR_TARGET_LIMIT,
            "radar_min_abs_move_pct": RADAR_MIN_ABS_MOVE_PCT,
            "radar_allow_yahoo_trending_fallback": RADAR_ALLOW_YAHOO_TRENDING_FALLBACK,
        },
        "session_settings": {
            "market_timezone": MARKET_TIMEZONE,
            "premarket_open": PREMARKET_OPEN,
            "regular_market_open": REGULAR_MARKET_OPEN,
            "regular_market_close": REGULAR_MARKET_CLOSE,
            "after_hours_close": AFTER_HOURS_CLOSE,
            "scan_extended_hours": SCAN_EXTENDED_HOURS,
            "allow_extended_hours_trading": ALLOW_EXTENDED_HOURS_TRADING,
            "stop_outside_rth": STOP_OUTSIDE_RTH,
            "global_overnight_open": GLOBAL_OVERNIGHT_OPEN,
            "global_overnight_close": GLOBAL_OVERNIGHT_CLOSE,
            "scan_global_overnight": SCAN_GLOBAL_OVERNIGHT,
            "scan_sunday_night": SCAN_SUNDAY_NIGHT,
            "allow_global_overnight_trading": ALLOW_GLOBAL_OVERNIGHT_TRADING,
        },
        "llm_settings": {
            "ollama_model": OLLAMA_MODEL,
            "ollama_url": OLLAMA_URL,
            "ollama_model_routing_enabled": OLLAMA_MODEL_ROUTING_ENABLED,
            "ollama_live_model": OLLAMA_LIVE_MODEL,
            "ollama_scanner_model": OLLAMA_SCANNER_MODEL,
            "ollama_news_model": OLLAMA_NEWS_MODEL,
            "ollama_deep_model": OLLAMA_DEEP_MODEL,
            "ollama_edge_model": OLLAMA_EDGE_MODEL,
            "ollama_gaming_model": OLLAMA_GAMING_MODEL,
            "llm_scanner_timeout_seconds": LLM_SCANNER_TIMEOUT_SECONDS,
            "llm_scanner_num_predict": LLM_SCANNER_NUM_PREDICT,
            "llm_scanner_keep_alive": LLM_SCANNER_KEEP_ALIVE,
            "llm_scanner_max_tickers": LLM_SCANNER_MAX_TICKERS,
            "llm_scanner_max_consecutive_failures": LLM_SCANNER_MAX_CONSECUTIVE_FAILURES,
            "signal_quality_filter_enabled": SIGNAL_QUALITY_FILTER_ENABLED,
            "signal_quality_min_score": SIGNAL_QUALITY_MIN_SCORE,
            "signal_quality_fail_open": SIGNAL_QUALITY_FAIL_OPEN,
            "signal_quality_fail_open_on_parse_error": SIGNAL_QUALITY_FAIL_OPEN_ON_PARSE_ERROR,
            "signal_quality_timeout_seconds": SIGNAL_QUALITY_TIMEOUT_SECONDS,
            "signal_quality_num_predict": SIGNAL_QUALITY_NUM_PREDICT,
            "signal_quality_retry_attempts": SIGNAL_QUALITY_RETRY_ATTEMPTS,
            "signal_quality_keep_alive": SIGNAL_QUALITY_KEEP_ALIVE,
            "execution_gate_timeout_seconds": EXECUTION_GATE_TIMEOUT_SECONDS,
            "execution_gate_num_predict": EXECUTION_GATE_NUM_PREDICT,
            "execution_gate_retry_attempts": EXECUTION_GATE_RETRY_ATTEMPTS,
            "execution_gate_keep_alive": EXECUTION_GATE_KEEP_ALIVE,
            "tech_news_llm_enabled": TECH_NEWS_LLM_ENABLED,
            "tech_news_relevance_filter_enabled": TECH_NEWS_RELEVANCE_FILTER_ENABLED,
            "tech_news_relevance_min_score": TECH_NEWS_RELEVANCE_MIN_SCORE,
            "tech_news_llm_max_items": TECH_NEWS_LLM_MAX_ITEMS,
            "tech_news_llm_batch_size": TECH_NEWS_LLM_BATCH_SIZE,
            "tech_news_llm_timeout_seconds": TECH_NEWS_LLM_TIMEOUT_SECONDS,
            "tech_news_llm_keep_alive": TECH_NEWS_LLM_KEEP_ALIVE,
        },
        "performance_settings": {
            "performance_governor_enabled": PERFORMANCE_GOVERNOR_ENABLED,
            "performance_mode": PERFORMANCE_MODE,
            "busy_cpu_percent": PERFORMANCE_BUSY_CPU_PCT,
            "gaming_cpu_budget_percent": PERFORMANCE_GAMING_CPU_BUDGET_PCT,
            "gaming_interval_multiplier": PERFORMANCE_GAMING_INTERVAL_MULTIPLIER,
            "gaming_max_num_predict": PERFORMANCE_GAMING_MAX_NUM_PREDICT,
            "gaming_max_batch_size": PERFORMANCE_GAMING_MAX_BATCH_SIZE,
            "gaming_max_llm_items": PERFORMANCE_GAMING_MAX_LLM_ITEMS,
            "gaming_max_workers": PERFORMANCE_GAMING_MAX_WORKERS,
            "gaming_max_llm_tickers": PERFORMANCE_GAMING_MAX_LLM_TICKERS,
            "gaming_throttle_enabled": PERFORMANCE_GAMING_THROTTLE_ENABLED,
            "gaming_throttle_min_sleep_seconds": PERFORMANCE_GAMING_THROTTLE_MIN_SLEEP_SECONDS,
            "gaming_throttle_max_sleep_seconds": PERFORMANCE_GAMING_THROTTLE_MAX_SLEEP_SECONDS,
            "gaming_process_priority": PERFORMANCE_GAMING_PROCESS_PRIORITY,
            "deferred_tasks": [item.strip() for item in PERFORMANCE_DEFER_TASKS.split(",") if item.strip()],
        },
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


def sync_runtime_config(dry_run=False):
    payload = build_runtime_config_snapshot()

    if dry_run:
        print(json.dumps(payload, indent=2, sort_keys=True))
        return payload

    supabase = get_supabase_client()
    supabase.table("bot_runtime_config").upsert(payload, on_conflict="id").execute()
    print(f"Runtime config synced to Supabase at {payload['updated_at']}.")
    return payload


def parse_args():
    parser = argparse.ArgumentParser(description="Sync live bot runtime settings to Supabase for SignalCenter.")
    parser.add_argument("--dry-run", action="store_true", help="Print the snapshot without writing to Supabase.")
    return parser.parse_args()


def main():
    args = parse_args()
    sync_runtime_config(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
