import os
import time
import pandas as pd
import yfinance as yf

from config import get_supabase_client
from signal_utils import insert_signal_with_cooldown

# --- CONFIGURATION ---
supabase = get_supabase_client()

def load_daily_targets():
    """Reads the daily target tickers generated by the category scanner."""
    file_path = os.path.join(os.path.dirname(__file__), "daily_targets.txt")
    if not os.path.exists(file_path):
        print("No daily_targets.txt found. Did the category scanner run?")
        return []
        
    try:
        with open(file_path, "r") as f:
            content = f.read().strip()
            if not content:
                return []
            # Split by comma and clean up whitespace to form the active list
            return [ticker.strip() for ticker in content.split(',')]
    except Exception as e:
        print(f"🚨 Failed to read local targets: {e}")
        return []

def calculate_rsi(ticker):
    """Fetches live market data and calculates the Relative Strength Index (RSI)."""
    try:
        data = yf.download(ticker, period="60d", interval="1d", progress=False)
        
        if data.empty:
            return None
            
        delta = data['Close'].diff()
        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)
        
        avg_gain = gain.ewm(com=14 - 1, min_periods=14).mean()
        avg_loss = loss.ewm(com=14 - 1, min_periods=14).mean()
        
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        
        val = rsi.iloc[-1]
        if isinstance(val, pd.Series):
            return float(val.iloc[0])
        return float(val)
        
    except Exception as e:
        print(f"⚠️ Error calculating data for {ticker}: {e}")
        return None

def push_signal_to_ipad(ticker, action, rsi_value, memo):
    """Uploads the generated signal to Supabase."""
    confidence = 0.85 if action == "BUY" else 0.80 
    
    payload = {
        "ticker": ticker,
        "action_type": action,
        "confidence_score": confidence,
        "investment_memo": memo,
        "status": "pending",
        "channel": "TECHNICAL"
    }
    
    try:
        if insert_signal_with_cooldown(supabase, payload, channel="TECHNICAL"):
            print(f"📡 SIGNAL TRANSMITTED: {action} {ticker} sent to iPad Dashboard.")
    except Exception as e:
        print(f"🚨 Supabase Upload Error: {e}")

def run_market_scan():
    print("🤖 AI Technical Researcher Online. Commencing Market Scan...")
    print("-" * 50)
    
    # --- THE HANDOFF ---
    watchlist = load_daily_targets()
    
    if not watchlist:
        print("🛑 Execution Halted: Watchlist is empty.")
        return
        
    print(f"Loaded {len(watchlist)} daily category targets for technical screening.")
    
    for ticker in watchlist:
        print(f"🔍 Analyzing {ticker}...")
        rsi = calculate_rsi(ticker)
        
        if rsi is None:
            continue
            
        print(f"   ↳ Current RSI: {rsi:.2f}")
        
        if rsi < 30:
            memo = f"Technical Breakout Scanner detected an extreme OVERSOLD condition (RSI: {rsi:.2f}). The stock has been heavily sold off and mathematical mean-reversion suggests a high probability of an upward bounce."
            push_signal_to_ipad(ticker, "BUY", rsi, memo)
            
        elif rsi > 70:
            memo = f"Technical Breakout Scanner detected an extreme OVERBOUGHT condition (RSI: {rsi:.2f}). The stock is mathematically over-extended and a pullback or correction is highly probable."
            push_signal_to_ipad(ticker, "SELL", rsi, memo)
            
        else:
            print(f"   ↳ State: Neutral. No edge detected. Skipping.")
            
        time.sleep(1)
        
    print("-" * 50)
    print("✅ Market Scan Complete. Check your iPad.")

if __name__ == "__main__":
    run_market_scan()
