import os
import time
import pandas as pd
import yfinance as yf

from config import (
    TECH_BUY_CONFIDENCE,
    TECH_RSI_BUY_THRESHOLD,
    TECH_RSI_SELL_THRESHOLD,
    TECH_SELL_CONFIDENCE,
    get_supabase_client,
)
from signal_utils import insert_signal_with_cooldown

# --- CONFIGURATION ---
supabase = get_supabase_client()

def load_daily_targets():
    """Reads the daily target tickers generated by the category scanner."""
    file_path = os.path.join(os.path.dirname(__file__), "daily_targets.txt")
    if not os.path.exists(file_path):
        print("No daily_targets.txt found. Did the category scanner run?")
        return []
        
    try:
        with open(file_path, "r") as f:
            content = f.read().strip()
            if not content:
                return []
            # Split by comma and clean up whitespace to form the active list
            return [ticker.strip() for ticker in content.split(',')]
    except Exception as e:
        print(f"🚨 Failed to read local targets: {e}")
        return []

def calculate_rsi(ticker):
    """Fetches live market data and calculates the Relative Strength Index (RSI)."""
    try:
        data = yf.download(ticker, period="60d", interval="1d", progress=False)
        
        if data.empty:
            return None
            
        delta = data['Close'].diff()
        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)
        
        avg_gain = gain.ewm(com=14 - 1, min_periods=14).mean()
        avg_loss = loss.ewm(com=14 - 1, min_periods=14).mean()
        
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        
        val = rsi.iloc[-1]
        if isinstance(val, pd.Series):
            return float(val.iloc[0])
        return float(val)
        
    except Exception as e:
        print(f"⚠️ Error calculating data for {ticker}: {e}")
        return None

def push_signal_to_ipad(ticker, action, rsi_value, memo):
    """Uploads the generated signal to Supabase."""
    confidence = TECH_BUY_CONFIDENCE if action == "BUY" else TECH_SELL_CONFIDENCE
    
    payload = {
        "ticker": ticker,
        "action_type": action,
        "confidence_score": confidence,
        "investment_memo": memo,
        "status": "pending",
        "channel": "TECHNICAL"
    }
    
    try:
        if insert_signal_with_cooldown(supabase, payload, channel="TECHNICAL"):
            print(f"📡 SIGNAL TRANSMITTED: {action} {ticker} sent to iPad Dashboard.")
    except Exception as e:
        print(f"🚨 Supabase Upload Error: {e}")

def run_market_scan():
    print("🤖 AI Technical Researcher Online. Commencing Market Scan...")
    print("-" * 50)
    
    # --- THE HANDOFF ---
    watchlist = load_daily_targets()
    
    if not watchlist:
        print("🛑 Execution Halted: Watchlist is empty.")
        return
        
    print(f"Loaded {len(watchlist)} daily category targets for technical screening.")
    print(
        "Technical thresholds: "
        f"BUY RSI <= {TECH_RSI_BUY_THRESHOLD:g}; "
        f"SELL RSI >= {TECH_RSI_SELL_THRESHOLD:g}"
    )
    
    for ticker in watchlist:
        print(f"🔍 Analyzing {ticker}...")
        rsi = calculate_rsi(ticker)
        
        if rsi is None:
            continue
            
        print(f"   ↳ Current RSI: {rsi:.2f}")
        
        if rsi <= TECH_RSI_BUY_THRESHOLD:
            memo = (
                f"Technical Scanner detected an oversold bounce setup (RSI: {rsi:.2f}, "
                f"threshold <= {TECH_RSI_BUY_THRESHOLD:g}). The stock is materially sold off "
                "and may be setting up for a mean-reversion move."
            )
            push_signal_to_ipad(ticker, "BUY", rsi, memo)
            
        elif rsi >= TECH_RSI_SELL_THRESHOLD:
            memo = (
                f"Technical Scanner detected an overbought caution setup (RSI: {rsi:.2f}, "
                f"threshold >= {TECH_RSI_SELL_THRESHOLD:g}). The stock is extended and may be "
                "vulnerable to a pullback."
            )
            push_signal_to_ipad(ticker, "SELL", rsi, memo)
            
        else:
            print(f"   ↳ State: Neutral. No edge detected. Skipping.")
            
        time.sleep(1)
        
    print("-" * 50)
    print("✅ Market Scan Complete. Check your iPad.")

if __name__ == "__main__":
    run_market_scan()
